name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run inside Termux Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            termux/termux-docker:aarch64 \
            sh -c "
              set -e
              pkg update -y
              pkg install -y rust
              cargo --version
              rustc --version
            "
            
