name: learn and test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      

      - name: Install build dependencies and test
        run: |
          git clone --depth 1 https://codeberg.org/Ryamos/SharpPawn.git
          cd SharpPawn
          dotnet build
          ls
