name: Build learn 

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          # Specify the exact semantic version you need
          version: 4.3.0
          # Set to true if you are using the C# / .NET version of Godot
          use-dotnet: false
          # Set to true to automatically download Godot's export templates
          include-templates: true

      # 3. Verify the installation or run your build/export commands
      - name: Verify Godot Installation
        run: |
          godot --version
