name: Build 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify installation
        run: |
            git clone --depth 1 --recursive https://codeberg.org/skyjake/lagrange.git
            cd lagrange
            mkdir build 
            cd build 
            cmake ..
            make -j 4
            ls
            
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-name
          path: Clock/app/build/outputs
    
